name: omnisms
description: Omnisms App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  firebase_messaging: ^14.7.0
  
  # Audio/Record FIXÃ‰
  record: ^5.0.0
  flutter_sound: ^9.2.13
  
  # Ads
  google_mobile_ads: ^3.1.0
  
  # Utils
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  url_launcher: ^6.1.0
  uuid: ^4.0.0
  webview_flutter: ^4.4.0
  provider: ^6.1.0
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  
  # UI/UX Enhancements
  flutter_animate: ^4.2.0
  google_fonts: ^6.1.0
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
