name: omnisms
description: Omnisms App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  firebase_messaging: ^15.2.10
  
  # Audio/Record FIXÃ‰
  record: 5.2.1
  flutter_sound: ^9.30.0
  
  # Ads
  google_mobile_ads: ^4.0.0
  
  # Utils
  shared_preferences: ^2.4.18
  path_provider: ^2.5.1
  url_launcher: ^6.3.6
  uuid: ^4.5.2
  webview_flutter: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
