name: omni_sms
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # ✅ Compatible Dart 3.5.x stable 2026
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  http: ^1.0.0
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  google_mobile_ads: ^7.0.0
  flutter_sound: ^9.28.0
  record: ^6.1.2
  shared_preferences: ^2.2.2
  startapp_sdk: ^1.0.1
  firebase_auth: ^6.1.3
  url_launcher: ^6.1.10
  web_socket_channel: ^3.0.3
  logger: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3  # ✅ Version stable Dart 3.5.x

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
